require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - config/initializers/tg_🐺♋🖼️_stickers_🌶️🍆💦.rb

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    ["app/controllers/telegram_webhooks_controller/authorization_handler.rb"]

Style/GuardClause:
  Exclude:
    ["app/controllers/telegram_webhooks_controller/authorization_handler.rb"]

Style/ModuleFunction:
  Exclude: ["app/controllers/telegram_webhooks_controller/summarize_helpers.rb"]

Style/OpenStructUse:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#'] # Allow long comments

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/AsciiIdentifiers:
  AsciiConstants: false

Style/NumericLiterals:
  Exclude: ["spec/**/*"]

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude: ["**/spec/requests/telegram_webhooks_controller/*"]

RSpec/VerifiedDoubleReference:
  Enabled: false

FactoryBot/ExcessiveCreateList:
  Enabled: false
