require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude: ['app/controllers/telegram_webhooks_controller/authorization_handler.rb']

Style/GuardClause:
  Exclude: ['app/controllers/telegram_webhooks_controller/authorization_handler.rb']

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#'] # Allow long comments

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
