### Add configs to both of these to prevent dev env from stealing prod bot messasges:
###   rails credentials:edit # for development/test
###   rails credentials:edit --environment=production

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: secureKeyBase123456789

# If enabled, bot will refuse to run in non-whitelisted chats
whitelist_enabled: true
chat_id_whitelist:
  - -4276127923 # Some telegram chat ID
  - -4276127174 # Some other chat

# Where to register telegram webhooks -- only needed for production
host_url: example.herokuapp.com

telegram:
  bot:
    token: TOKEN
    username: SomeBot
    # async: true # uncomment in production

# Any OpenAI-compatible API like Huggingface, Groq, etc
openai:
  access_token: yourAccessToken
  uri_base: https://api-inference.huggingface.co/v1/
  model: Mixtral-8x7B-Instruct-v0.1 # 32K context
  # model: meta-llama/Meta-Llama-3-70B-Instruct - 8K context kinda small
