### Add configs to both of these to prevent dev env from stealing prod bot messasges:
###   rails credentials:edit # for development/test
###   rails credentials:edit --environment=production

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: secureKeyBase123456789

# If enabled, bot will refuse to run in non-whitelisted chats
whitelist_enabled: true
chat_id_whitelist:
  - -4276127923 # Some telegram chat ID
  - -4276127174 # Some other chat

# Where to register telegram webhooks -- only needed for production
# because in development the bot just polls telegram's servers
host_url: example.herokuapp.com

telegram:
  bot:
    # async: true # UNCOMMENT IN PRODUCTION
    token: TOKEN
    username: SomeBot # without the @
    first_name: DogBot # "Name" in BotFather settings
    owner_username: yourTgUsername # without the @

# Any OpenAI-compatible API like Huggingface, Groq, etc
openai:
  access_token: yourAccessToken
  uri_base: https://api-inference.huggingface.co/v1/
  model: meta-llama/Meta-Llama-3.1-70B-Instruct # 32K context
  # translate_model: CohereForAI/aya-23-8B # optional, use different model for translation
  translate_languages: # list of supported languages for matching against `/translate [language] text`
    - Arabic
    - Chinese
    - Czech
    - Dutch
    - English
    - French
    - German
    - Greek
    - Hebrew
    - Hindi
    - Indonesian
    - Italian
    - Japanese
    - Korean
    - Persian
    - Polish
    - Portuguese
    - Romanian
    - Russian
    - Spanish
    - Turkish
    - Ukrainian
    - Vietnamese
