### Add configs to both of these to prevent dev env stealing bot registration:
###   rails credentials:edit # for development/test
###   rails credentials:edit --environment=production

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: secureKeyBase123456789

# Bot will refuse to run in non-whitelisted chats
chat_id_whitelist:
  - -4276127923 # Some telegram chat ID
  - -4276127174 # Some other chat

# Where to register telegram webhooks -- only needed for production
host_url: example.herokuapp.com

telegram:
  bot:
    token: TOKEN
    username: SomeBot
    # async: true # uncomment in production
