### Add configs to both of these to prevent dev env stealing bot registration:
###   rails credentials:edit # for development/test
###   rails credentials:edit --environment=production

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: secureKeyBase123456789

telegram:
  bot:
    token: TOKEN
    username: SomeBot
    # async: true # uncomment in production
