### Add configs to both of these to prevent dev env from stealing prod bot messasges:
###   rails credentials:edit # for development/test
###   rails credentials:edit --environment=production

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: secureKeyBase123456789

# If enabled, bot will refuse to run in non-whitelisted chats
whitelist_enabled: true
chat_id_whitelist:
  - -4276127923 # Some telegram chat ID
  - -4276127174 # Some other chat

# Where to register telegram webhooks -- only needed for production
# because in development the bot just polls telegram's servers
host_url: example.herokuapp.com

telegram:
  bot:
    token: TOKEN
    username: SomeBot # without the @
    # async: true # UNCOMMENT IN PRODUCTION


models:
  # OpenAI-compatible API example (huggingface, groq, etc)
  llama-3.1-70b:
    type: openai
    access_token: yourAccessToken
    uri_base: https://api-inference.huggingface.co/v1/
    model: meta-llama/Meta-Llama-3.1-70B-Instruct # 32K context
  # Self-hosted koboldcpp example
  aya-23-35b:
    type: koboldcpp
    access_token: yourAccessToken # 'password' in koboldcpp config
    uri_base: https://your-server.ai/ # will attempt to use /api/v1 so don't put that here


# Model to use for summarize functions.
summarize:
  # Must match an entry under `models` key declared above
  model: llama-3.1-70b
  model_config:
    temperature: 1.0


# Model to use for translate functions
translate:
  # Must match an entry under `models` key declared above
  model: aya-23-35b
  model_config:
    temperature: 0.3

  # Optionally specify fallback for when server can't connect to API
  fallback_model: llama-3.1-70b
  fallback_model_config:
    temperature: 1.0

  # list of supported languages for matching against `/translate [language] text`
  languages:
    - Arabic
    - Chinese
    - Czech
    - Dutch
    - English
    - French
    - German
    - Greek
    - Hebrew
    - Hindi
    - Indonesian
    - Italian
    - Japanese
    - Korean
    - Persian
    - Polish
    - Portuguese
    - Romanian
    - Russian
    - Spanish
    - Turkish
    - Ukrainian
    - Vietnamese
